AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for  tool-permission-proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    Architectures:
      - arm64
    Api:

      Cors:

        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"

        AllowHeaders: "'Content-Type,Authorization'"

        AllowOrigin: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  MockCRMFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mock_crm/
      Handler: app.lambda_handler
      Runtime: python3.13
      Policies:
       - DynamoDBCrudPolicy:
           TableName: Customers
      Environment:
        Variables:
            CUSTOMERS_TABLE: Customers
      Events:
        GetCustomer:
          Type: Api
          Properties:
            Path: /crm/customers/{id}
            Method: get
        ListCustomers:
          Type: Api
          Properties:
            Path: /crm/customers
            Method: get
        UpdateCustomer:
          Type: Api
          Properties:
            Path: /crm/customers/{id}
            Method: put
        DeleteCustomer:
          Type: Api
          Properties:
            Path: /crm/customers/{id}
            Method: delete
            
  PermissionProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: permission_proxy/
      Handler: app.lambda_handler
      Runtime: python3.13
      Policies:
       - DynamoDBCrudPolicy:
           TableName: AuditLogs
       - DynamoDBCrudPolicy:
           TableName: SecurityAlerts

      Environment:
        Variables:
          AUDIT_TABLE: AuditLogs
          SECURITY_ALERT_TABLE: SecurityAlerts
      Events:
        ProxyRequest:
          Type: Api
          Properties:
            Path: /proxy/{proxy+}
            Method: ANY

  AIAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          GEMINI_API_KEY: "AIzaSyAjJQDxY1-WnWPxJAsK4hZZ_aR9KVwJPDE"
      CodeUri: ai_agent/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 15
      MemorySize: 512
      Events:
        Agent:
          Type: Api
          Properties:
            Path: /agent
            Method: post
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Customers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: customer_id
          KeyType: HASH
  SecurityAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecurityAlerts
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S

      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
